name: Test workflow
run-name: Test workflow ${{ github.run_number }}

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'

permissions: 
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump Env context
        run: echo '${{ toJSON(env) }}'
      - name: Dump Matrix context
        run: echo '${{ toJSON(matrix) }}'

  Build-Matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [{toto: "0", tutu: "0"}, {toto: "0", tutu: "1"}, {toto: "1", tutu: "0"}, {toto :"1", tutu: "1"}]
    steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump Env context
        run: echo '${{ toJSON(env) }}'
      - name: Dump Matrix context
        run: echo '${{ toJSON(matrix) }}'
