name: Matrix test workflow
run-name: Matrix test workflow ${{ github.run_number }}

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  # schedule:
  #   - cron: '15 6 * * 0'

permissions: 
  contents: read

jobs:
  Build:
    needs: call-job-dump-context
    runs-on: ubuntu-latest
    steps:
      - name: valid
        run: echo ok

  call-job-dump-context:
    uses: ./.github/workflows/dump-context.yml

  Build-Matrix:
    needs: call-job-dump-context-matrix
    runs-on: ubuntu-latest
    steps:
      - name: valid
        run: echo ok

  call-job-dump-context-matrix:
    uses: ./.github/workflows/dump-context.yml
    strategy:
      matrix:
        testing: ["0", "1"]
